Stephs Shop/Models/Customer.cs
namespace Stephs_Shop.Models
{
    public class Customer
    {
        public string id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string addressline3 { get; set;}
        public string postalcode { get; set; }
    }
}

Stephs Shop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stephs_Shop.Models
{
    public class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
        public string image_url { get; set; }
        public int inventory_id { get; set; }
        public int category_id { get; set; }
        public DateTimeOffset created_at { get; set; }
        public DateTimeOffset modified_at { get; set; }
        public DateTimeOffset deleted_at { get; set; }

    }
}

Stephs Shop/Areas/Admin/Controllers/OfficeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.VisualStudio.Web.CodeGeneration;
using Newtonsoft.Json;
using Stephs_Shop.Models;
using Stephs_Shop.NewFolder;
using Stephs_Shop.Repositories;
using Stephs_Shop.Services;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Stephs_Shop.Areas.Admin.Controllers
{
	[Area("Admin")]
	[ServiceFilter(typeof(CustomerDataInjectior))]
	[Authorize(Roles = "Admin")]
	public class OfficeController : Controller
	{
		private readonly IProductRepository _productRepository;
		private readonly IReportRepository _reportRepository;
		private readonly IFileService _fileService;
		private readonly ILogger<OfficeController> _logger;

		private readonly ICustomerRepository _customerRepository;
		public OfficeController(IProductRepository productRepository, 
			IReportRepository reportRepository,
			IFileService fileService,
			ICustomerRepository customerRepository,
			ILogger<OfficeController> logger)
		{
			_productRepository = productRepository;
			_reportRepository = reportRepository;
			_fileService= fileService;
			_logger = logger;
			_customerRepository = customerRepository;
		}


		[HttpGet]
		public async Task<IActionResult> Dashboard()
		{
			ViewData["Title"] = "Dashboard.View";
			var dashboardReport = await _reportRepository.GetDashBoardReport().ConfigureAwait(false);
			ViewBag.Dashboard = dashboardReport;
			return View();
		}

		[HttpGet]
		public async Task<IActionResult> Product()
		{
			ViewData["Title"] = "Product.View";
			ViewBag.Products = await _productRepository.GetAllProduct().ConfigureAwait(false);
			ViewBag.Category = await _productRepository.GetProductCategory().ConfigureAwait(false);
			return View();
		}


		[HttpPost]
		public async Task<IActionResult> AddProduct(string name, string description, IFormFile image , decimal price)
																																																																																																																																							{
			if (ModelState.IsValid)
			{
				var filename = image.FileName;
				var content = filename.Split(".")[1];
				var contentType = image.ContentType;
				List<Binary> binary = new List<Binary>();
				List<byte[]> filebytes =  new List<byte[]>();
				if (! new[]{ "png", "jpg", "jpeg" }.Contains(content))
				{
					return BadRequest("File type must be jpg or png");
				}
				
				//file must not be greater than 7MB
				if(image.Length < 0 && image.Length > 7340032)
				{
					return BadRequest("Image size must not be more than 3mb");
				}
				using(var filestream = image.OpenReadStream())
				using(MemoryStream ms = new MemoryStream())
				{
					filestream.CopyTo(ms);
					//binary.Add(ms.ToArray());
					filebytes.Add(ms.ToArray());
					Binary fileBinary = new Binary(ms.ToArray(), filename);
					_fileService.uploadFile(fileBinary);
					_logger.LogDebug("File Uploaded Successfully");
				}
				Product product = new Product
				{
					price = price,
					name = name,
					description = description,
				};

				await _productRepository.AddProduct(product).ConfigureAwait(false);
				_logger.LogInformation("Product created successfully");
				return Ok("Product Added successfully");
			}

			return BadRequest();
		}


		public async Task<IActionResult> CustomerView(int limit = 50 , int sortBy = 0, int page = 0)
		{
			ViewData["Title"] = "Customer.View";
			var customers = await _customerRepository.GetAllCustomers().ConfigureAwait(false);
			int customer_count = customers.Count();
			limit = limit > customer_count ? limit : customer_count;
			int offset = (page - 1) * limit;
            ViewBag.page_count = Math.Ceiling((double)customer_count / limit);
			
			ViewBag.Customers = customers;
			return View();
		}



		[HttpPost]
		public async Task<IActionResult> SearchCustomer(string searchTerm)
		{
			ViewBag.Customers = await _customerRepository.FetchCustomers(searchTerm).ConfigureAwait(false);
			return View(nameof(CustomerView));
		}

		public async Task<IActionResult> AdvancedSearch(string address, int customerId, DateTime startDate, DateTime endDate )
		{
			if (ModelState.IsValid)
			{

				return Ok();
			}
			return BadRequest();
		}
		
		

	}
}

Stephs Shop/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace Stephs_Shop.Areas.Admin.Controllers
{
	public class ProductController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Stephs Shop/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RestSharp;
using Stephs_Shop.Models;
using Stephs_Shop.Models.Entities;
using Stephs_Shop.Repositories;
using Stephs_Shop.Services;
using System;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Transactions;

namespace Stephs_Shop.Controllers
{
	public class CustomerController : BaseController
	{
		private readonly ICustomerRepository _customerRepository;
		private readonly IOrderRepository _orderRepository;
		private readonly ICartRepository cartRepository;
		private readonly IProductRepository _productRepository;
		private readonly ILogger<CustomerController> _logger;
		private readonly IEmailSender _emailSender;
		private readonly HttpClient _client;
		public CustomerController(IOrderRepository orderRepository,
			ICartRepository cartRepository,
			IProductRepository productRepository, 
			ILogger<CustomerController> logger,
			IEmailSender emailSender,
			UserManager<User> userManager,
			SignInManager<User> signInManager) : base(userManager, signInManager)
		{
			_orderRepository = orderRepository;
			this.cartRepository = cartRepository;
			_productRepository = productRepository;
			_logger = logger;
			_emailSender = emailSender;
			_client = new HttpClient();
		}
		public IActionResult Index()
		{
			return View();
		}


		[HttpPost]
		public async Task<IActionResult> MakeTransaction(Product[] products, decimal amount, int quantity, decimal price)
		{
			//do checks for parameter
			if(ModelState.IsValid)
			{
				var user = await GetCurrentUser();
				if(quantity < 0)
				{
					return BadRequest("Quantity must be more than zero");
				}
				decimal sum = 0;
				foreach(var item in products)
				{
					
					var product = await _productRepository.GetProduct(item.id).ConfigureAwait(false);
					//remove this
					if(product == null)
					{
						return BadRequest("Product doesnt exists");
					}
					sum += item.price;

				}
				//decimal sum = product.Select(c=>c.price).Sum();
				if(amount < sum)
				{
					return BadRequest("Amount paid is less the price of products");
				}
				
				using (var transaction = new TransactionScope())
				{
					try
					{
						RestClient restClient = new RestClient();
						//make payment 

						//add cart




						using(TransactionScope transactionScope = new TransactionScope())
						{
                            //add orders
                            var order_id = await _orderRepository.AddOrderDetail(user.Id, 0);	
                            await _orderRepository.AddOrderItem();

                            //create transaction for payment



                            //


                        }


                    }
					catch (Exception ex)
					{
						_logger.LogCritical($"Error Message: {ex.Message}");
						throw new Exception(ex.Message);              

					}

					return StatusCode(200, new {});
				}
			}

			return BadRequest();
			
			

		}
	}
}

Stephs Shop/Areas/Admin/Views/Office/CustomerView.cshtml
@{
	Layout = null;
	var status = "active";
}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="img/icons/icon-48x48.png" />
	<link rel="canonical" href="https://demo-basic.adminkit.io/" />
	<title> Dashboard </title>
	<link href="~/css/admin.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/admin.css" />
	<link rel="stylesheet" href="~/css/styles.css" />

</head>

<body>
	<div class="wrapper">
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">
				<a class="sidebar-brand" href="index.html">
					<span class="align-middle">Dashboard </span>
				</a>
				<ul class="sidebar-nav">
					<li class="sidebar-header">
						Pages
					</li>

					<li class="sidebar-item active">
						<a class="sidebar-link" href="index.html">
							<i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Dashboard</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-profile.html">
							<i class="align-middle" data-feather="user"></i> <span class="align-middle">Profile</span>
						</a>
					</li>


					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-blank.html">
							<i class="align-middle" data-feather="user-plus"></i> <span class="align-middle">Manage Users</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-blank.html">
							<i class="align-middle" data-feather="package"></i> <span class="align-middle">Manage Products</span>
						</a>
					</li>


					<li class="sidebar-item">
						<a class="sidebar-link" href="pages-blank.html">
							<i class="align-middle" data-feather="box"></i> <span class="align-middle">Manage orders</span>
						</a>
					</li>


					<li class="sidebar-item">
						<a class="sidebar-link" href="ui-forms.html">
							<i class="align-middle" data-feather="check-square"></i> <span class="align-middle">Forms</span>
						</a>
					</li>

					<li class="sidebar-header">
						Other Services
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="charts-chartjs.html">
							<i class="align-middle" data-feather="bar-chart-2"></i> <span class="align-middle">Product Inventory</span>
						</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="maps-google.html">
							<i class="align-middle" data-feather="map"></i> <span class="align-middle">Maps</span>
						</a>
					</li>
				</ul>
			</div>
		</nav>

		<div class="main">
			<nav class="navbar navbar-expand navbar-light navbar-bg">
				<a class="sidebar-toggle js-sidebar-toggle">
					<i class="hamburger align-self-center"></i>
				</a>

				<div class="navbar-collapse collapse">
					<ul class="navbar-nav navbar-align">
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle" href="#" id="alertsDropdown" data-bs-toggle="dropdown">
								<div class="position-relative">
									<i class="align-middle" data-feather="bell"></i>
									<span class="indicator">4</span>
								</div>
							</a>
							<div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="alertsDropdown">
								<div class="dropdown-menu-header">
									4 New Notifications
								</div>
								<div class="list-group">
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<i class="text-danger" data-feather="alert-circle"></i>
											</div>
											<div class="col-10">
												<div class="text-dark">Update completed</div>
												<div class="text-muted small mt-1">Restart server 12 to complete the update.</div>
												<div class="text-muted small mt-1">30m ago</div>
											</div>
										</div>
									</a>
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<i class="text-warning" data-feather="bell"></i>
											</div>
											<div class="col-10">
												<div class="text-dark">Lorem ipsum</div>
												<div class="text-muted small mt-1">Aliquam ex eros, imperdiet vulputate hendrerit et.</div>
												<div class="text-muted small mt-1">2h ago</div>
											</div>
										</div>
									</a>
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<i class="text-primary" data-feather="home"></i>
											</div>
											<div class="col-10">
												<div class="text-dark">Login from 192.186.1.8</div>
												<div class="text-muted small mt-1">5h ago</div>
											</div>
										</div>
									</a>
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<i class="text-success" data-feather="user-plus"></i>
											</div>
											<div class="col-10">
												<div class="text-dark">New connection</div>
												<div class="text-muted small mt-1">Christina accepted your request.</div>
												<div class="text-muted small mt-1">14h ago</div>
											</div>
										</div>
									</a>
								</div>
								<div class="dropdown-menu-footer">
									<a href="#" class="text-muted">Show all notifications</a>
								</div>
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle" href="#" id="messagesDropdown" data-bs-toggle="dropdown">
								<div class="position-relative">
									<i class="align-middle" data-feather="message-square"></i>
								</div>
							</a>
							<div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="messagesDropdown">
								<div class="dropdown-menu-header">
									<div class="position-relative">
										4 New Messages
									</div>
								</div>
								<div class="list-group">
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<img src="img/avatars/avatar-5.jpg" class="avatar img-fluid rounded-circle" alt="Vanessa Tucker">
											</div>
											<div class="col-10 ps-2">
												<div class="text-dark">Vanessa Tucker</div>
												<div class="text-muted small mt-1">Nam pretium turpis et arcu. Duis arcu tortor.</div>
												<div class="text-muted small mt-1">15m ago</div>
											</div>
										</div>
									</a>
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<img src="img/avatars/avatar-2.jpg" class="avatar img-fluid rounded-circle" alt="William Harris">
											</div>
											<div class="col-10 ps-2">
												<div class="text-dark">William Harris</div>
												<div class="text-muted small mt-1">Curabitur ligula sapien euismod vitae.</div>
												<div class="text-muted small mt-1">2h ago</div>
											</div>
										</div>
									</a>
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<img src="img/avatars/avatar-4.jpg" class="avatar img-fluid rounded-circle" alt="Christina Mason">
											</div>
											<div class="col-10 ps-2">
												<div class="text-dark">Christina Mason</div>
												<div class="text-muted small mt-1">Pellentesque auctor neque nec urna.</div>
												<div class="text-muted small mt-1">4h ago</div>
											</div>
										</div>
									</a>
									<a href="#" class="list-group-item">
										<div class="row g-0 align-items-center">
											<div class="col-2">
												<img src="img/avatars/avatar-3.jpg" class="avatar img-fluid rounded-circle" alt="Sharon Lessman">
											</div>
											<div class="col-10 ps-2">
												<div class="text-dark">Sharon Lessman</div>
												<div class="text-muted small mt-1">Aenean tellus metus, bibendum sed, posuere ac, mattis non.</div>
												<div class="text-muted small mt-1">5h ago</div>
											</div>
										</div>
									</a>
								</div>
								<div class="dropdown-menu-footer">
									<a href="#" class="text-muted">Show all messages</a>
								</div>
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
								<i class="align-middle" data-feather="settings"></i>
							</a>

							<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
								<img src="img/avatars/avatar.jpg" class="avatar img-fluid rounded me-1" alt="Charles Hall" /> <span class="text-dark">Charles Hall</span>
							</a>
							<div class="dropdown-menu dropdown-menu-end">
								<a class="dropdown-item" href="pages-profile.html"><i class="align-middle me-1" data-feather="user"></i> Profile</a>
								<a class="dropdown-item" href="#"><i class="align-middle me-1" data-feather="pie-chart"></i> Analytics</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="index.html"><i class="align-middle me-1" data-feather="settings"></i> Settings & Privacy</a>
								<a class="dropdown-item" href="#"><i class="align-middle me-1" data-feather="help-circle"></i> Help Center</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="#">Log out</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>

			<main class="content pt-2">
				<div class="container">
					
					<div class="col-lg-6 col-6 text-left mx-auto px-4">
						<form  asp-controller="Office" asp-action="SearchCustomer" method="post">
							<div class="input-group">
								<input type="text" class="form-control" name="searchterm" placeholder="Search for Customers">
								<div class="input-group-append">
									<button type="submit">
										<span class="input-group-text bg-transparent text-primary">
											<i class="fa-search"></i>
										</span>
									</button>

								</div>
							</div>
						</form>
					</div>

					<div class="table-responsive">

						<table class="table custom-table">
							<thead>
								<tr>
									<th scope="col">
										<label class="control control--checkbox">
											<input type="checkbox" class="js-check-all" />
											<div class="control__indicator"></div>
										</label>
									</th>
									<th scope="col">FirstName</th>
									<th scope="col">LastName</th>
									<th scope="col">Occupation</th>
									<th scope="col">Email</th>
									<th scope="col">Education</th>
								</tr>
							</thead>
							<tbody>
								@foreach(var customer in ViewBag.Customers)
								{
									<tr>
										<th scope="row">
											<label class="control control--checkbox">
												<input type="checkbox" />
												<div class="control__indicator"></div>
											</label>
										</th>
										<td>
											@customer.firstname
										</td>
										<td>@customer.lastname</td>
										<td>
											Web Designer
											<small class="d-block">Far far away, behind the word mountains</small>
										</td>
										<td> @customer.email </td>
										<td> @customer.addressline1 </td>
									</tr>
								}
								
								
							</tbody>

						</table>
						<div p-2>
							<ul class="pagination pl-4 pe-4 ">
								
								<li class="page-item @if (true)
								{
									@status
								} ">
									<a class="page-link">Previous</a>
								</li
								@for(int i =1; i < ViewBag.page_count; i++)
								{
									<li class="page-item">
									<a class="page-link" asp-page="@i"> @i </a>
								</li>
								}
								<li class="page-item">
									<a class="page-link">Next</a>
								</li>

							</ul>
						</div>
					</div>

				</div>

			</main>


		</div>
	</div>

	<script src="~/js/app.js"></script>

	<script>
		document.addEventListener("DOMContentLoaded", function () {
			var date = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000);
			var defaultDate = date.getUTCFullYear() + "-" + (date.getUTCMonth() + 1) + "-" + date.getUTCDate();
			document.getElementById("datetimepicker-dashboard").flatpickr({
				inline: true,
				prevArrow: "<span title=\"Previous month\">&laquo;</span>",
				nextArrow: "<span title=\"Next month\">&raquo;</span>",
				defaultDate: defaultDate
			});
		});
	</script>
</body>

</html>

Stephs Shop/Areas/Admin/Views/Office/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}